services:
  db:
    ports: !reset []
    restart: unless-stopped

  api:
    ports: !reset []
    restart: unless-stopped

  web:
    ports: !reset []
    restart: unless-stopped

  nginx:
    ports: !override
      - "80:80"
      - "443:443"
    volumes:
      - ${NGINX_CONF:-./docker/nginx/nginx.http.conf}:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    restart: unless-stopped
