services:
  db:
    ports: []
    restart: unless-stopped

  api:
    ports: []
    restart: unless-stopped

  web:
    ports: []
    restart: unless-stopped

  nginx:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    restart: unless-stopped
